import React from 'react';
import { useApp } from '../../context/AppContext';
import { Leaf, Zap, Activity, Sun, Thermometer, Wind, Award, BarChart3 } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';

const ECO_TREND = [
  { day: 'Mon', co2SavedTonnes: 12.4, evMiles: 4800 },
  { day: 'Tue', co2SavedTonnes: 13.1, evMiles: 5100 },
  { day: 'Wed', co2SavedTonnes: 14.2, evMiles: 5450 },
  { day: 'Thu', co2SavedTonnes: 13.8, evMiles: 5200 },
  { day: 'Fri', co2SavedTonnes: 15.6, evMiles: 6100 },
  { day: 'Sat', co2SavedTonnes: 16.2, evMiles: 6300 },
  { day: 'Sun', co2SavedTonnes: 14.8, evMiles: 5900 },
];

export const EcoAnalytics: React.FC = () => {
  const { environmental } = useApp();

  return (
    <div className="p-4 md:p-6 max-w-6xl mx-auto space-y-6 text-slate-100">
      
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Leaf className="w-5 h-5 text-emerald-400" />
            <h2 className="text-xl font-extrabold text-white tracking-tight">
              Environmental Monitoring & Carbon Credit Dashboard
            </h2>
          </div>
          <p className="text-xs text-slate-400">
            Real-time urban micro-climate analytics, air quality monitoring, and public fleet carbon offset ledger.
          </p>
        </div>

        <div className="flex items-center gap-2 bg-emerald-950/80 border border-emerald-800/80 px-3.5 py-2 rounded-2xl text-xs">
          <Award className="w-4 h-4 text-emerald-400" />
          <span>City Sustainability Rating: <strong className="text-emerald-300 font-extrabold">A+ Green Metro</strong></span>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        
        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-2">
          <span className="text-xs font-semibold text-slate-400 flex items-center gap-1.5">
            <Wind className="w-4 h-4 text-cyan-400" /> Air Quality Index
          </span>
          <div className="text-3xl font-extrabold text-emerald-400 font-mono">{environmental.aqi}</div>
          <p className="text-xs text-slate-400">Status: <strong className="text-emerald-300">{environmental.status}</strong></p>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-2">
          <span className="text-xs font-semibold text-slate-400 flex items-center gap-1.5">
            <Zap className="w-4 h-4 text-amber-400" /> CO₂ Offset Today
          </span>
          <div className="text-3xl font-extrabold text-amber-300 font-mono font-bold">
            {(environmental.co2OffsetTodayKg / 1000).toFixed(1)} t
          </div>
          <p className="text-xs text-slate-400">Target: <strong className="text-slate-200">20.0 t / day</strong></p>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-2">
          <span className="text-xs font-semibold text-slate-400 flex items-center gap-1.5">
            <Activity className="w-4 h-4 text-purple-400" /> Ambient Noise
          </span>
          <div className="text-3xl font-extrabold text-purple-300 font-mono font-bold">{environmental.noiseLevelDb} dB</div>
          <p className="text-xs text-slate-400">Within Quiet Zone Limits</p>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-2">
          <span className="text-xs font-semibold text-slate-400 flex items-center gap-1.5">
            <Sun className="w-4 h-4 text-amber-400" /> Solar Bus Stop Yield
          </span>
          <div className="text-3xl font-extrabold text-white font-mono">148 kWh</div>
          <p className="text-xs text-emerald-400 font-semibold">100% Self-Powered Displays</p>
        </div>

      </div>

      {/* Chart Section */}
      <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-bold text-sm text-white">Weekly CO₂ Avoided via Electrified Transit (Tonnes)</h3>
            <p className="text-xs text-slate-400 font-normal">Tracking carbon credits generated by zero-emission buses & metro line</p>
          </div>
          <span className="text-[10px] uppercase font-bold text-emerald-400 bg-emerald-950 px-2.5 py-0.5 rounded border border-emerald-800">
            Verified Carbon Credits
          </span>
        </div>

        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={ECO_TREND}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="day" stroke="#64748b" fontSize={11} />
              <YAxis stroke="#64748b" fontSize={11} />
              <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', color: '#fff', borderRadius: '12px', fontSize: '12px' }} />
              <Bar dataKey="co2SavedTonnes" name="CO₂ Saved (Tonnes)" fill="#00E676" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

    </div>
  );
};
